sonar.verbose=true
sonar.organization=kitty-trends-key
sonar.projectKey=kitty-trends-key_kitty-trends-project
sonar.projectName=kitty-trends-project
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
